---
- name: Ensure required packages are installed
  apt: pkg={{ item }} state=present
  with_items:
    - libpam-google-authenticator
    - libpam0g-dev
    - libqrencode4

- name: Copy the PAM RADIUS auth file
  #notify: restart freeradius
  copy:
    src: etc/pam.d/radiusd
    dest: /etc/pam.d/radiusd
    owner: root
    group: root
    mode: '0644'
    backup: yes
